name: Simple CI

on:
  push:
    branches: [main]

jobs:
  check-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: List Files
        run: ls -la
