name: Simple CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FEATURE_VACATION_TRACKING: 1  # Change to 0 to disable feature

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || echo "No requirements.txt found, skipping install"

      - name: Run Unit Tests
        run: pytest tests/ --disable-warnings
        continue-on-error: false

      - name: Check Code Formatting (Black)
        run: black --check .

      - name: Set Feature Flag Output
        id: feature_check
        run: |
          if [[ "$FEATURE_VACATION_TRACKING" == "1" ]]; then
            echo "enabled=true" >> $GITHUB_ENV
          else
            echo "enabled=false" >> $GITHUB_ENV
          fi

      - name: Run Vacation Tracking Feature Tests
        if: env.enabled == 'true'
        run: echo "Feature is enabled, running vacation tracking tests!"

      - name: List Files (Debug Step)
        run: ls -la